apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-blog.fullname" . }}-config
  labels:
    {{- include "django-blog.labels" . | nindent 4 }}
data:
  DB_HOST: {{ include "django-blog.databaseHost" . | quote }}
  DB_PORT: {{ include "django-blog.databasePort" . | quote }}
  DB_USER: {{ include "django-blog.databaseUser" . | quote }}
  DB_NAME: {{ include "django-blog.databaseName" . | quote }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.django.allowedHosts | quote }}
  DJANGO_DEBUG: {{ .Values.django.debug | quote }}
  TIME_ZONE: {{ .Values.django.timeZone | quote }}
