apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-blog.fullname" . }}-secrets
  labels:
    {{- include "django-blog.labels" . | nindent 4 }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.django.secretKey | b64enc }}
  DB_PASSWORD: {{ if .Values.postgresql.enabled }}{{ .Values.postgresql.auth.password | b64enc }}{{ else }}{{ .Values.externalDatabase.password | b64enc }}{{ end }}
