# Generated by Django 5.2.14 on 2026-07-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_published', '-created_at'], name='post_pub_created_idx'),
        ),
    ]
